export const IPC_CHANNELS = {
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  listAudioOutputs: "devices:list-audio-output",
  serviceStart: "service:start",
  serviceStop: "service:stop",
  queueSkip: "queue:skip",
  queuePauseToggle: "queue:pause-toggle",
  queueStop: "queue:stop",
  queueClear: "queue:clear",
  queueAdd: "queue:add",
  queueRemove: "queue:remove",
  stateUpdate: "state:update",
  playbackStart: "playback:start",
  playbackStop: "playback:stop",
  playbackPause: "playback:pause",
  playbackResume: "playback:resume",
  setupRconRequired: "setup:rcon-required",
  playbackReady: "playback:ready",
  playbackEnded: "playback:ended",
  playbackError: "playback:error",
  logAppend: "log:append"
} as const;
